FROM python:3.12-slim

WORKDIR /app

COPY dependencies/requirements.dev.txt .
RUN pip install --no-cache-dir -r requirements.dev.txt

COPY src/ .

CMD ["fastapi", "dev", "app.py", "--port", "8000", "--host", "0.0.0.0"]