services:
  redis:
    image: redis:latest
    container_name: redis_prod
    ports:
      - "6379:6379"
  hello-app:
    build:
      context: ../
      dockerfile: Dockerfile.prod
    container_name: hello-app
    ports:
      - "8000:8000"
    env_file:
      - ../env/prod.env
    depends_on:
      - redis
  fluentd:
    image: fluent/fluentd:v1.14-1
    container_name: fluentd_prod
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    env_file:
      - ../env/prod.env